export default function About() {
  return (
    <div className="py-20 px-4 max-w-6xl mx-auto">
      <h1 className="text-3xl font-bold mb-4 text-slate-800 ">Real Estify</h1>
      <p className="mb-4 text-slate-700">Welcome to RealEstify, your ultimate destination for finding your perfect home. At RealEstify, we believe in making the process of buying, renting, or selling a home as seamless as possible. Our platform offers a wide range of properties, tailored to meet the diverse needs and preferences of our clients. Whether you're looking for a cozy apartment in the city, a spacious family home in the suburbs, or a lucrative investment property, RealEstify has it all. Our team of dedicated professionals is committed to providing exceptional service, ensuring that your real estate journey is both enjoyable and successful. Explore our listings today and discover why RealEstify is the best place to find your next perfect place to live.</p>
      <p className="mb-4 text-slate-700"><span className="text-3xl font-bold mb-4 text-slate-800" >Buying a home</span> is a significant milestone, and at RealEstify, we make it a rewarding experience. Our extensive listings feature a variety of homes to suit every budget and lifestyle, from modern condos to charming single-family houses. With advanced search filters and detailed property descriptions, finding your dream home has never been easier. Our experienced agents are here to guide you through every step of the process, providing expert advice and support. Whether you're a first-time buyer or looking to upgrade, RealEstify ensures you find a home that meets your needs and exceeds your expectations. Start your home-buying journey with us and turn your homeownership dreams into reality.</p>
      <p className="mb-4 text-slate-700"><span className="text-3xl font-bold mb-4 text-slate-800">Renting a Home</span>Finding the perfect rental property can be a daunting task, but RealEstify makes it simple and stress-free. Our platform features a comprehensive selection of rental homes, including apartments, houses, and townhomes, in prime locations. With user-friendly search tools and detailed listings, you can easily find a rental that fits your lifestyle and budget. At RealEstify, we understand the importance of flexibility and convenience, offering short-term and long-term rental options to meet your specific needs. Our dedicated team is here to assist you in finding the perfect rental home, ensuring a smooth and enjoyable renting experience. Discover the best rental properties with RealEstify today.</p>
      <p className="mb-4 text-slate-700"><span className="text-3xl font-bold mb-4 text-slate-800">Selling Your Home</span>When it comes to selling your home, RealEstify provides the expertise and resources needed to achieve the best results. Our platform offers powerful marketing tools to showcase your property to a wide audience of potential buyers. With detailed property listings, high-quality photos, and virtual tours, we ensure your home stands out in the market. Our team of professional real estate agents works closely with you to develop a personalized selling strategy, from setting the right price to negotiating offers. At RealEstify, we are committed to making the selling process efficient and successful, helping you get the maximum value for your home. Trust us to handle your home sale with care and professionalism.</p>
    </div>
  )
}